Rails.application.config.assets.precompile += %w( jquery-1.10.2.js )
Rails.application.config.assets.precompile += %w( bootstrap.js )
Rails.application.config.assets.precompile += %w( freelancer.css )
Rails.application.config.assets.precompile += %w( font-awesome.min.css )
Rails.application.config.assets.precompile += %w( bootstrap.css )
Rails.application.config.assets.precompile += %w( classie.js )
Rails.application.config.assets.precompile += %w( freelancer.js )
Rails.application.config.assets.precompile += %w( cbpAnimatedHeader.js )